### ISSUE TITLE
crashed GNOME

### ISSUE THREAD

**Issue by SolarAquarion** [leeter/hexchat#9]
while it was booting up it crashed GNOME

**Comment by leeter** [comment]
@SolarAquarion are you sure you're filing this against the right version of hexchat? This particular build is beta at best (listed as experimental) and is not supported on any platform. Did you intend for this to be against [Hexchat proper](https://github.com/hexchat/hexchat)?

**Comment by SolarAquarion** [comment]
I'm filing against this one.  Actually cpp-dev.  It happens while loading
channel's

**Comment by leeter** [comment]
given that it works on my machines both windows 10 and ubuntu 15.04 (GCC 4.9.2) I'm going to leave this closed unless you can provide more information. And given the nature of that branch.... a stack trace.

**Comment by SolarAquarion** [comment]
Gdb I guess?

**Comment by leeter** [comment]
I'll also need to know which commit you're compiling against.

**Comment by SolarAquarion** [comment]
cpp-dev and latest.  Hmm, it has crashed on hexchat before because I have a
lot of logs.

**Comment by SolarAquarion** [comment]
That's not the issue

**Comment by leeter** [comment]
@SolarAquarion I need:
- OS
- Compiler version
- GDB stacktrace
- Build options if any
- What's crashing is it fe-gtk or fe-text?
- what plugins are you using?

**Comment by SolarAquarion** [comment]
Arch Linux

GCC 5.2

--prefix=/u/usr  --enable-textfe --enable-python=Python3 --disable-debug

No plugins

**Comment by SolarAquarion** [comment]
hexchat-text                                                     ⮂
[09:36:17]
[09:36:17]  HexChat-Text 2.11.0
[09:36:17]  Running on  glib 2.44.1
[09:36:17]  This binary compiled Aug  9 2015
[09:36:17]
[09:36:17]
[09:36:17] Compiled in Features: Plugin NLS OpenSSL IPv6
[09:36:17]
[09:36:17] SysInfo plugin loaded
[09:36:17] Do At plugin loaded
[09:36:17] Python interface loaded
[09:36:17] FiSHLiM plugin loaded
[09:36:17] Checksum plugin loaded
[09:36:17] AutoLoad failed for: /usr/lib/hexchat/plugins/perl.so
[09:36:17] No hexchat_plugin_init symbol; is this really a HexChat plugin?
[09:36:17] \* Connected. Now logging in.
[09:36:17] \* Connected. Now logging in.
[09:36:17] \* Connected. Now logging in.
[09:36:17] \* **\* Looking up your hostname...
[09:36:17] Network is unreachable
[09:36:17] 101
[1]    19426 killed     hexchat-text

**Comment by leeter** [comment]
at the moment hexchat-text is not actively supported, I'll look into it when I get time.

**Comment by SolarAquarion** [comment]
Well, the issue came up in hexchat gtk and well, there was no debugging
stuff available according to gdb

**Comment by TingPing** [comment]
I have also seen this issue in normal hexchat, I always guessed xtext was redrawing so much it crashes X.

**Comment by leeter** [comment]
@TingPing if this was the main build I would buy that, as the main build draws all over the place. Particularly when it's not supposed to (like anywhere BUT the expose/draw event) but mine just queue's redraws where it would draw directly.

**Comment by leeter** [comment]
@SolarAquarion how hexchat-text is crashing gnome is something I chalk up to arch though. it's a terminal program so the terminal itself would have to crash gnome. That said it is crashing on my machine at the same place with `SIGKILL`

**Comment by SolarAquarion** [comment]
How would I get a gdb stacktrace on your build?  I enabled build debug but
it's the same size as before.  I tried to use gnu ddd to get debug stuff
but it didn't work.

**Comment by SolarAquarion** [comment]
Hexchat-text isn't crashing gnome/X.  Hexchat-gtk is

**Comment by leeter** [comment]
@SolarAquarion there will be no stacktrace for the crash for hexchat-text. As for hexchat-gtk you'd have to attach GDB to it and see where it's crashing, I know there is memory corruption in `xtext.cpp` I get heap corruption crashes on windows, but without addresssanitizer they are near impossible to track down on windows. Unfortunately Ubuntu doesn't yet support GCC5 and the accompanying libstdc++ which uses the short string optimization (like VC++ does on windows). So it's near impossible at this time for me to track that buffer overrun down. If you can build with address sanitizer and Undefined behavior sanitizer that would help.

**Comment by SolarAquarion** [comment]
./configure options for that?

**Comment by leeter** [comment]
```
./configure --enable-textfe --with-theme-manager  CFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-common -fdiagnostics-color=always" CPPFLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer -fno-common -fdiagnostics-color=always" LIBS="-lasan -lubsan"
```
